//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boo.BooLangProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boo.BooLangProject.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the dll or exe file.
        /// </summary>
        internal static string AssemblyNameDescription {
            get {
                return ResourceManager.GetString("AssemblyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: BooBinPath registry key is not set. Please create the registry key &apos;HKLM\SOFTWARE\BooLangStudio@BooBinPath&apos;, and set the value to be the path to your installation of Boo..
        /// </summary>
        internal static string BooBinPathMissing {
            get {
                return ResourceManager.GetString("BooBinPathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Namespace.
        /// </summary>
        internal static string DefaultNamespace {
            get {
                return ResourceManager.GetString("DefaultNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the default namespace for added items, such as classes, that are added via the Add New Item Dialog Box..
        /// </summary>
        internal static string DefaultNamespaceDescription {
            get {
                return ResourceManager.GetString("DefaultNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ducky.
        /// </summary>
        internal static string Ducky {
            get {
                return ResourceManager.GetString("Ducky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on or off ducky behavior.
        /// </summary>
        internal static string DuckyDescription {
            get {
                return ResourceManager.GetString("DuckyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Type.
        /// </summary>
        internal static string OutputType {
            get {
                return ResourceManager.GetString("OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of application to build..
        /// </summary>
        internal static string OutputTypeDescription {
            get {
                return ResourceManager.GetString("OutputTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitespace agnostic.
        /// </summary>
        internal static string WhiteSpaceAgnostic {
            get {
                return ResourceManager.GetString("WhiteSpaceAgnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on or off whitespace agnostic behavior.
        /// </summary>
        internal static string WhiteSpaceAgnosticDescription {
            get {
                return ResourceManager.GetString("WhiteSpaceAgnosticDescription", resourceCulture);
            }
        }
    }
}
